services:
  db:
    container_name: "postgres-database"
    image: postgres:14
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
