services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.1.5
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
