apiVersion: 1

deleteDatasources:
  - name: Loki
    orgId: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki_datasource
    url: http://loki:3100
    password:
    user:
    database:
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: false
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
